Separate into multiple steps

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -7,10 +7,38 @@ on:
 jobs:
 
   build:
-    name: Build, Unit Test, and Install Ruby
+    name: Build and Test
     runs-on: ubuntu-latest
-    steps:
+    env:
+      TENANT_ID: Test
+      TOOLCHAIN_ID: 55446d64-25c7-40a0-9af9-440d1b409f76
+      ELASTIC_URL: https://c9acb36a-0feb-4b6e-aac1-6651c71d19e4.2adb0220806343e3ae11df79c89b377f.databases.appdomain.cloud:32085
+      ELASTIC_CERT_FILE: elastic-cert64
+      ELASTIC_USER: ibm_cloud_1a27be2f_c7eb_4395_9cc4_71940b7f75d8
+      COS_URL: https://s3.us-east.cloud-object-storage.appdomain.cloud
+      IAM_CLOUD_URL: https://iam.cloud.ibm.com
+      EVENTSTREAMS_BROKERS: broker-0-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-1-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-2-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-3-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-4-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-5-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093
+      ASOC_CLI_URL: https://cloud.appscan.com/api/SCX/StaticAnalyzer/SAClientUtil?os=linux
+      ASOC_APP_ID: eba1dccd-b68d-4df4-9522-9718e5324b55
+      ASOC_KEY_ID: d8bc6fa7-993d-30e4-a735-333c77ccceac
+      OCTOKIT_API_ENDPOINT: https://github.com/api/v3
+      REGION: us-east
+      RESOURCE_GROUP: hri-dev1-wdc-kube
+      ELASTIC_INSTANCE: hri-dev1-elasticsearch-v7
+      ELASTIC_SVC_ACCOUNT: elastic-search-credential
+      KAFKA_INSTANCE: hri-dev1-event-streams
+      KAFKA_SVC_ACCOUNT: event-streams-credential
+      HRI_URL: https://localhost:1323/hri
+      CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
+      ELASTIC_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
+      ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
+      FN_WEB_SECURE_KEY: ${{ secrets.FN_WEB_SECURE_KEY }}
+      HRI_API_KEY: ${{ secrets.HRI_API_KEY }}
+      GIT_API_KEY: ${{ secrets.GIT_API_KEY }}
+      KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
+      ASOC_KEY_SECRET: ${{ secrets.ASOC_KEY_SECRET }}
 
+    steps:
     - name: Set up Go 1.13
       uses: actions/setup-go@v2
       with:
@@ -19,7 +47,17 @@ jobs:
     - name: Check out code into the Go module directory
       uses: actions/checkout@v2
 
-    - name: Install Ruby Gems
+    - name: Build Executable and Run Unit Tests
+      run: |
+        curl -sL https://ibm.biz/idt-installer | bash
+        go get -u github.com/jstemmer/go-junit-report
+        ibmcloud login --apikey $CLOUD_API_KEY -r us-east || { echo 'IBM Cloud CLI login failed!'; travis_terminate 1; }
+        ./run-unittests.sh
+
+    - name: Run Smoke Tests
+      run: ./run-smoketests.sh
+
+    - name: Install Ruby
       run: |
         gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
         curl -sSL https://get.rvm.io | bash -s stable --ruby
@@ -28,38 +66,3 @@ jobs:
         rvm list
         gem install bundler
         BUNDLE_GEMFILE="./test/Gemfile" bundle install
-        curl -sL https://ibm.biz/idt-installer | bash
-        ibmcloud plugin install doi
-        go get -u github.com/jstemmer/go-junit-report
-        ibmcloud login --apikey $CLOUD_API_KEY -r us-east || { echo 'IBM Cloud CLI login failed!'; travis_terminate 1; }
-        ibmcloud plugin install event-streams
-        ./run-unittests.sh
-        ./run-smoketests.sh
-      env:
-        TENANT_ID: Test
-        TOOLCHAIN_ID: 55446d64-25c7-40a0-9af9-440d1b409f76
-        ELASTIC_URL: https://c9acb36a-0feb-4b6e-aac1-6651c71d19e4.2adb0220806343e3ae11df79c89b377f.databases.appdomain.cloud:32085
-        ELASTIC_CERT_FILE: elastic-cert64
-        ELASTIC_USER: ibm_cloud_1a27be2f_c7eb_4395_9cc4_71940b7f75d8
-        COS_URL: https://s3.us-east.cloud-object-storage.appdomain.cloud
-        IAM_CLOUD_URL: https://iam.cloud.ibm.com
-        EVENTSTREAMS_BROKERS: broker-0-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-1-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-2-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-3-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-4-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-5-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093
-        ASOC_CLI_URL: https://cloud.appscan.com/api/SCX/StaticAnalyzer/SAClientUtil?os=linux
-        ASOC_APP_ID: eba1dccd-b68d-4df4-9522-9718e5324b55
-        ASOC_KEY_ID: d8bc6fa7-993d-30e4-a735-333c77ccceac
-        OCTOKIT_API_ENDPOINT: https://github.com/api/v3
-        REGION: us-east
-        RESOURCE_GROUP: hri-dev1-wdc-kube
-        ELASTIC_INSTANCE: hri-dev1-elasticsearch-v7
-        ELASTIC_SVC_ACCOUNT: elastic-search-credential
-        KAFKA_INSTANCE: hri-dev1-event-streams
-        KAFKA_SVC_ACCOUNT: event-streams-credential
-        HRI_URL: https://localhost:1323/hri
-        CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
-        ELASTIC_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
-        ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
-        FN_WEB_SECURE_KEY: ${{ secrets.FN_WEB_SECURE_KEY }}
-        HRI_API_KEY: ${{ secrets.HRI_API_KEY }}
-        GIT_API_KEY: ${{ secrets.GIT_API_KEY }}
-        KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
-        ASOC_KEY_SECRET: ${{ secrets.ASOC_KEY_SECRET }}
